In [6]:
import pandas as pd
import random
import os
import numpy as np

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

abcde 각각 해석해서 이름 붙이기

In [8]:
#parquet -> 대용량 데이터셋을 다루기 위한 확장자
#csv -> 24만권 => 1. 신용정보, ... , 8. 8개의 정보 프래임을 열은 다 살리고 중복 열만 죽임
#열 갯수 -> 700개

In [9]:
train_path = '/content/drive/MyDrive/블루문/card_train.csv'
test_path = '/content/drive/MyDrive/블루문/card_test.csv'

In [10]:
train_df = pd.read_csv(train_path)

In [11]:
train_df .shape

(70560, 738)

In [12]:
train_df.head()

,Unnamed: 0.1,대표결제일,대표결제방법코드,대표청구지고객주소구분코드,대표청구서수령지구분코드,청구서수령방법,청구서발송여부_B0,청구서발송여부_R3M,청구서발송여부_R6M,청구금액_B0,...,컨택건수_CA_청구서_R6M,컨택건수_이용유도_청구서_R6M,컨택건수_이용유도_인터넷_R6M,컨택건수_이용유도_당사앱_R6M,컨택건수_채권_B0M,컨택건수_채권_R6M,캠페인접촉건수_R12M,캠페인접촉일수_R12M,ID,Segment.1
0,61865,1,자동이체,주거지,우편,우편,1,1,1,466,...,0,5,5,0,0,0,1회 이상,1일 이상,TRAIN_000389,E
1,8547,13,자동이체,미확인,이메일,이메일,1,1,1,2417,...,0,4,6,0,0,0,1회 이상,1일 이상,TRAIN_304152,D
2,43497,25,자동이체,주거지,우편,우편,0,0,0,0,...,2,4,2,0,0,0,5회 이상,5일 이상,TRAIN_356239,E
3,40785,25,자동이체,주거지,우편,우편,1,1,1,5931,...,0,0,0,0,0,0,1회 이상,1일 이상,TRAIN_122432,E
4,18999,25,자동이체,주거지,우편,우편,1,1,1,684,...,2,0,0,0,0,0,10회 이상,10일 이상,TRAIN_285200,E

In [13]:
for i in train_df.columns:
  print(i)

Unnamed: 0.1
대표결제일
대표결제방법코드
대표청구지고객주소구분코드
대표청구서수령지구분코드
청구서수령방법
청구서발송여부_B0
청구서발송여부_R3M
청구서발송여부_R6M
청구금액_B0
청구금액_R3M
청구금액_R6M
포인트_마일리지_건별_B0M
포인트_마일리지_건별_R3M
포인트_포인트_건별_B0M
포인트_포인트_건별_R3M
포인트_마일리지_월적립_B0M
포인트_마일리지_월적립_R3M
포인트_포인트_월적립_B0M
포인트_포인트_월적립_R3M
포인트_적립포인트_R12M
포인트_적립포인트_R3M
포인트_이용포인트_R12M
포인트_이용포인트_R3M
포인트_잔여포인트_B0M
마일_적립포인트_R12M
마일_적립포인트_R3M
마일_이용포인트_R12M
마일_이용포인트_R3M
마일_잔여포인트_B0M
할인건수_R3M
할인금액_R3M
할인건수_B0M
할인금액_B0M
할인금액_청구서_R3M
할인금액_청구서_B0M
상환개월수_결제일_R6M
상환개월수_결제일_R3M
선결제건수_R6M
선결제건수_R3M
연체건수_R6M
연체건수_R3M
혜택수혜금액_R3M
포인트_마일리지_환산_B0M
혜택수혜금액
최초한도금액
카드이용한도금액
CA한도금액
일시상환론한도금액
월상환론한도금액
CA이자율_할인전
CL이자율_할인전
RV일시불이자율_할인전
RV현금서비스이자율_할인전
RV신청일자
RV약정청구율
RV최소결제비율
자발한도감액횟수_R12M
자발한도감액금액_R12M
자발한도감액후경과월
강제한도감액횟수_R12M
강제한도감액금액_R12M
강제한도감액후경과월
한도증액횟수_R12M
한도증액금액_R12M
한도증액후경과월
상향가능한도금액
상향가능CA한도금액
카드론동의여부
월상환론상향가능한도금액
RV전환가능여부
일시불ONLY전환가능여부
카드이용한도금액_B1M
카드이용한도금액_B2M
특별한도보유여부_R3M
연체감액여부_R3M
한도심사요청건수
한도요청거절건수
한도심사요청후경과월
한도심사거절후경과월
시장단기연체여부_R6M
rv최초시작후경과일
증감율_이용건수_신용_전월
증감율_이용건수_신판_전월
증감율_이용건수_일시불_전월
증감율_이용건수_할부_전월
증감율_이용건수_CA_전월
증감율_이용건수_체크_전월
증감율_이용건수_카드론_전월
증감율_이용금액_신용_전월
증감율_이용금액_신판_전월
증감율_이용금액_일시불_전월
증감율_이용금액_할부_전월
증감율_이용금액_CA_전월
증감율_이용금액_체크_전월
증감율_이용금액_카드론_전월
증감율_이용건수_신용_분기
증감율_이용건수_신판_분기
증감율_이용건수_일시불_분기
증감율_이용건수_할부_분기
증감율_이용건수_CA_분기
증감율_이용건수_체크_분기
증감율_이용건수_카드론_분기
증감율_이용금액_신용_분기
증감율_이용금액_신판_분기
증감율_이용금액_일시불_분기
증감율_이용금액_할부_분기
증감율_이용금액_CA_분기
증감율_이용금액_체크_분기
증감율_이용금액_카드론_분기
잔액_신판평균한도소진율_r6m
잔액_신판최대한도소진율_r6m
잔액_신판평균한도소진율_r3m
잔액_신판최대한도소진율_r3m
잔액_신판ca평균한도소진율_r6m
잔액_신판ca최대한도소진율_r6m
잔액_신판ca평균한도소진율_r3m
잔액_신판ca최대한도소진율_r3m
변동률_일시불평잔
변동률_RV일시불평잔
변동률_할부평잔
변동률_CA평잔
변동률_RVCA평잔
변동률_카드론평잔
변동률_잔액_B1M
변동률_잔액_일시불_B1M
변동률_잔액_CA_B1M
혜택수혜율_R3M
혜택수혜율_B0M
Unnamed: 0
남녀구분코드
연령
Segment
회원여부_이용가능
회원여부_이용가능_CA
회원여부_이용가능_카드론
소지여부_신용
소지카드수_유효_신용
소지카드수_이용가능_신용
입회일자_신용
입회경과개월수_신용
회원여부_연체
이용거절여부_카드론
동의여부_한도증액안내
수신거부여부_TM
수신거부여부_DM
수신거부여부_메일
수신거부여부_SMS
가입통신회사코드
탈회횟수_누적
최종탈회후경과월
탈회횟수_발급6개월이내
탈회횟수_발급1년이내
거주시도명
직장시도명
마케팅동의여부
유효카드수_신용체크
유효카드수_신용
유효카드수_신용_가족
유효카드수_체크
유효카드수_체크_가족
이용가능카드수_신용체크
이용가능카드수_신용
이용가능카드수_신용_가족
이용가능카드수_체크
이용카드수_신용체크
이용카드수_신용
이용카드수_신용_가족
이용카드수_체크
이용금액_R3M_신용체크
이용금액_R3M_신용
이용금액_R3M_신용_가족
이용금액_R3M_체크
_1순위카드이용금액
_1순위카드이용건수
_1순위신용체크구분
_2순위카드이용금액
_2순위카드이용건수
_2순위신용체크구분
최종유효년월_신용_이용가능
최종유효년월_신용_이용
최종카드발급일자
보유여부_해외겸용_본인
이용가능여부_해외겸용_본인
이용여부_3M_해외겸용_본인
보유여부_해외겸용_신용_본인
이용가능여부_해외겸용_신용_본인
이용여부_3M_해외겸용_신용_본인
연회비발생카드수_B0M
기본연회비_B0M
제휴연회비_B0M
상품관련면제카드수_B0M
카드신청건수
Life_Stage
최종카드발급경과월
인입횟수_ARS_R6M
이용메뉴건수_ARS_R6M
인입일수_ARS_R6M
인입월수_ARS_R6M
인입후경과월_ARS
인입횟수_ARS_B0M
이용메뉴건수_ARS_B0M
인입일수_ARS_B0M
방문횟수_PC_R6M
방문일수_PC_R6M
방문월수_PC_R6M
방문후경과월_PC_R6M
방문횟수_앱_R6M
방문일수_앱_R6M
방문월수_앱_R6M
방문후경과월_앱_R6M
방문횟수_모바일웹_R6M
방문일수_모바일웹_R6M
방문월수_모바일웹_R6M
방문후경과월_모바일웹_R6M
방문횟수_PC_B0M
방문일수_PC_B0M
방문횟수_앱_B0M
방문일수_앱_B0M
방문횟수_모바일웹_B0M
방문일수_모바일웹_B0M
인입횟수_IB_R6M
인입일수_IB_R6M
인입월수_IB_R6M
이용메뉴건수_IB_R6M
인입후경과월_IB_R6M
인입횟수_IB_B0M
인입일수_IB_B0M
이용메뉴건수_IB_B0M
인입불만후경과월_IB_R6M
상담건수_B0M
IB문의건수_사용승인내역_B0M
IB문의건수_선결제_B0M
IB문의건수_CL_RV_B0M
IB문의건수_CS_B0M
상담건수_R6M
IB문의건수_사용승인내역_R6M
IB문의건수_한도_R6M
IB문의건수_선결제_R6M
IB문의건수_결제_R6M
IB문의건수_할부_R6M
IB문의건수_정보변경_R6M
IB문의건수_결제일변경_R6M
IB문의건수_비밀번호_R6M
IB문의건수_SMS_R6M
IB문의건수_포인트_R6M
IB문의건수_카드발급_R6M
IB문의건수_BL_R6M
IB문의건수_분실도난_R6M
IB문의건수_CA_R6M
IB문의건수_CL_RV_R6M
IB문의건수_CS_R6M
불만제기후경과월_R12M
당사멤버쉽_방문횟수_B0M
당사멤버쉽_방문횟수_R6M
당사멤버쉽_방문월수_R6M
OS구분코드
홈페이지_금융건수_R6M
홈페이지_선결제건수_R6M
홈페이지_금융건수_R3M
홈페이지_선결제건수_R3M
잔액_일시불_B0M
잔액_할부_B0M
잔액_현금서비스_B0M
잔액_리볼빙일시불이월_B0M
잔액_리볼빙CA이월_B0M
잔액_카드론_B0M
월중평잔_일시불_B0M
월중평잔_할부_B0M
월중평잔_CA_B0M
연체일자_B0M
연체잔액_B0M
연체잔액_일시불_B0M
연체잔액_할부_B0M
연체잔액_현금서비스_B0M
연체잔액_카드론_B0M
잔액_현금서비스_B1M
잔액_현금서비스_B2M
잔액_카드론_B1M
잔액_카드론_B2M
잔액_카드론_B3M
잔액_카드론_B4M
잔액_카드론_B5M
잔액_할부_B1M
잔액_할부_B2M
잔액_일시불_B1M
잔액_일시불_B2M
연체일수_B1M
연체일수_B2M
연체원금_B1M
연체원금_B2M
연체일수_최근
연체원금_최근
최종연체회차
RV_평균잔액_R12M
RV_최대잔액_R12M
RV_평균잔액_R6M
RV_최대잔액_R6M
RV_평균잔액_R3M
RV_최대잔액_R3M
잔액_할부_유이자_B0M
잔액_할부_무이자_B0M
잔액_할부_해외_B0M
연체잔액_RV일시불_B0M
연체잔액_CA_B0M
월중평잔
월중평잔_일시불
월중평잔_RV일시불
월중평잔_할부
월중평잔_CA
월중평잔_카드론
평잔_3M
평잔_일시불_3M
평잔_일시불_해외_3M
평잔_RV일시불_3M
평잔_RV일시불_해외_3M
평잔_할부_3M
평잔_할부_해외_3M
평잔_CA_3M
평잔_CA_해외_3M
평잔_카드론_3M
평잔_6M
평잔_일시불_6M
평잔_일시불_해외_6M
평잔_RV일시불_6M
평잔_RV일시불_해외_6M
평잔_할부_6M
평잔_할부_해외_6M
평잔_CA_6M
평잔_CA_해외_6M
평잔_카드론_6M
최종이용일자_기본
최종이용일자_신판
최종이용일자_CA
최종이용일자_카드론
최종이용일자_체크
최종이용일자_일시불
최종이용일자_할부
이용건수_신용_B0M
이용건수_신판_B0M
이용건수_일시불_B0M
이용건수_할부_B0M
이용건수_할부_유이자_B0M
이용건수_할부_무이자_B0M
이용건수_CA_B0M
이용건수_체크_B0M
이용건수_카드론_B0M
이용금액_일시불_B0M
이용금액_할부_B0M
이용금액_할부_유이자_B0M
이용금액_할부_무이자_B0M
이용금액_CA_B0M
이용금액_체크_B0M
이용금액_카드론_B0M
이용후경과월_신용
이용후경과월_신판
이용후경과월_일시불
이용후경과월_할부
이용후경과월_할부_유이자
이용후경과월_할부_무이자
이용후경과월_부분무이자
이용후경과월_CA
이용후경과월_체크
이용후경과월_카드론
이용건수_신용_R12M
이용건수_신판_R12M
이용건수_일시불_R12M
이용건수_할부_R12M
이용건수_할부_유이자_R12M
이용건수_할부_무이자_R12M
이용건수_부분무이자_R12M
이용건수_CA_R12M
이용건수_체크_R12M
이용건수_카드론_R12M
이용금액_일시불_R12M
이용금액_할부_R12M
이용금액_할부_유이자_R12M
이용금액_할부_무이자_R12M
이용금액_부분무이자_R12M
이용금액_CA_R12M
이용금액_체크_R12M
이용금액_카드론_R12M
최대이용금액_일시불_R12M
최대이용금액_할부_R12M
최대이용금액_할부_유이자_R12M
최대이용금액_할부_무이자_R12M
최대이용금액_부분무이자_R12M
최대이용금액_CA_R12M
최대이용금액_체크_R12M
최대이용금액_카드론_R12M
이용개월수_신용_R12M
이용개월수_신판_R12M
이용개월수_일시불_R12M
이용개월수_할부_R12M
이용개월수_할부_유이자_R12M
이용개월수_할부_무이자_R12M
이용개월수_부분무이자_R12M
이용개월수_CA_R12M
이용개월수_체크_R12M
이용개월수_카드론_R12M
이용건수_신용_R6M
이용건수_신판_R6M
이용건수_일시불_R6M
이용건수_할부_R6M
이용건수_할부_유이자_R6M
이용건수_할부_무이자_R6M
이용건수_부분무이자_R6M
이용건수_CA_R6M
이용건수_체크_R6M
이용건수_카드론_R6M
이용금액_일시불_R6M
이용금액_할부_R6M
이용금액_할부_유이자_R6M
이용금액_할부_무이자_R6M
이용금액_부분무이자_R6M
이용금액_CA_R6M
이용금액_체크_R6M
이용금액_카드론_R6M
이용개월수_신용_R6M
이용개월수_신판_R6M
이용개월수_일시불_R6M
이용개월수_할부_R6M
이용개월수_할부_유이자_R6M
이용개월수_할부_무이자_R6M
이용개월수_부분무이자_R6M
이용개월수_CA_R6M
이용개월수_체크_R6M
이용개월수_카드론_R6M
이용건수_신용_R3M
이용건수_신판_R3M
이용건수_일시불_R3M
이용건수_할부_R3M
이용건수_할부_유이자_R3M
이용건수_할부_무이자_R3M
이용건수_부분무이자_R3M
이용건수_CA_R3M
이용건수_체크_R3M
이용건수_카드론_R3M
이용금액_일시불_R3M
이용금액_할부_R3M
이용금액_할부_유이자_R3M
이용금액_할부_무이자_R3M
이용금액_부분무이자_R3M
이용금액_CA_R3M
이용금액_체크_R3M
이용금액_카드론_R3M
이용개월수_신용_R3M
이용개월수_신판_R3M
이용개월수_일시불_R3M
이용개월수_할부_R3M
이용개월수_할부_유이자_R3M
이용개월수_할부_무이자_R3M
이용개월수_부분무이자_R3M
이용개월수_CA_R3M
이용개월수_체크_R3M
이용개월수_카드론_R3M
이용가맹점수
이용금액_해외
쇼핑_도소매_이용금액
쇼핑_백화점_이용금액
쇼핑_마트_이용금액
쇼핑_슈퍼마켓_이용금액
쇼핑_편의점_이용금액
쇼핑_아울렛_이용금액
쇼핑_온라인_이용금액
쇼핑_기타_이용금액
교통_주유이용금액
교통_정비이용금액
교통_통행료이용금액
교통_버스지하철이용금액
교통_택시이용금액
교통_철도버스이용금액
여유_운동이용금액
여유_Pet이용금액
여유_공연이용금액
여유_공원이용금액
여유_숙박이용금액
여유_항공이용금액
여유_기타이용금액
납부_통신비이용금액
납부_관리비이용금액
납부_가스전기료이용금액
납부_보험료이용금액
납부_기타이용금액
_1순위업종
_1순위업종_이용금액
_2순위업종
_2순위업종_이용금액
_3순위업종
_3순위업종_이용금액
_1순위쇼핑업종
_1순위쇼핑업종_이용금액
_2순위쇼핑업종
_2순위쇼핑업종_이용금액
_3순위쇼핑업종
_3순위쇼핑업종_이용금액
_1순위교통업종
_1순위교통업종_이용금액
_2순위교통업종
_2순위교통업종_이용금액
_3순위교통업종
_3순위교통업종_이용금액
_1순위여유업종
_1순위여유업종_이용금액
_2순위여유업종
_2순위여유업종_이용금액
_3순위여유업종
_3순위여유업종_이용금액
_1순위납부업종
_1순위납부업종_이용금액
_2순위납부업종
_2순위납부업종_이용금액
_3순위납부업종
_3순위납부업종_이용금액
할부건수_3M_R12M
할부건수_6M_R12M
할부건수_12M_R12M
할부건수_14M_R12M
할부금액_3M_R12M
할부금액_6M_R12M
할부금액_12M_R12M
할부금액_14M_R12M
할부건수_유이자_3M_R12M
할부건수_유이자_6M_R12M
할부건수_유이자_12M_R12M
할부금액_유이자_3M_R12M
할부금액_유이자_6M_R12M
할부금액_유이자_12M_R12M
할부금액_유이자_14M_R12M
할부건수_무이자_3M_R12M
할부건수_무이자_6M_R12M
할부건수_무이자_12M_R12M
할부금액_무이자_3M_R12M
할부금액_무이자_6M_R12M
할부금액_무이자_12M_R12M
할부금액_무이자_14M_R12M
할부금액_부분_12M_R12M
할부금액_부분_14M_R12M
RP건수_B0M
RP금액_B0M
RP유형건수_B0M
RP건수_통신_B0M
RP건수_아파트_B0M
RP건수_제휴사서비스직접판매_B0M
RP건수_렌탈_B0M
RP건수_가스_B0M
RP건수_전기_B0M
RP건수_보험_B0M
RP건수_학습비_B0M
RP건수_교통_B0M
RP후경과월
RP후경과월_통신
RP후경과월_아파트
RP후경과월_제휴사서비스직접판매
RP후경과월_렌탈
RP후경과월_가스
RP후경과월_전기
RP후경과월_보험
RP후경과월_학습비
RP후경과월_교통
증감_RP건수_전월
증감_RP유형건수_전월
증감_RP건수_통신_전월
증감_RP건수_아파트_전월
증감_RP건수_제휴사서비스직접판매_전월
증감_RP건수_렌탈_전월
증감_RP건수_가스_전월
증감_RP건수_전기_전월
증감_RP건수_보험_전월
증감_RP건수_학습비_전월
증감_RP건수_교통_전월
최초카드론이용경과월
최종카드론이용경과월
카드론이용건수_누적
카드론이용월수_누적
카드론이용금액_누적
최종카드론_금융상환방식코드
최종카드론_신청경로코드
최종카드론_대출이율
최종카드론_대출일자
최종카드론_대출월수
최종카드론_거치개월수
최종카드론_대출금액
이용개월수_온라인_R6M
이용개월수_오프라인_R6M
이용금액_온라인_R6M
이용금액_오프라인_R6M
이용건수_온라인_R6M
이용건수_오프라인_R6M
이용금액_온라인_R3M
이용금액_오프라인_R3M
이용건수_온라인_R3M
이용건수_오프라인_R3M
이용금액_온라인_B0M
이용금액_오프라인_B0M
이용건수_온라인_B0M
이용건수_오프라인_B0M
이용개월수_페이_온라인_R6M
이용개월수_페이_오프라인_R6M
이용금액_페이_온라인_R6M
이용금액_페이_오프라인_R6M
이용건수_페이_온라인_R6M
이용건수_페이_오프라인_R6M
이용금액_페이_온라인_R3M
이용금액_페이_오프라인_R3M
이용건수_페이_온라인_R3M
이용건수_페이_오프라인_R3M
이용금액_페이_온라인_B0M
이용금액_페이_오프라인_B0M
이용건수_페이_온라인_B0M
이용건수_페이_오프라인_B0M
이용개월수_간편결제_R6M
이용개월수_당사기타_R6M
이용개월수_A페이_R6M
이용개월수_B페이_R6M
이용개월수_C페이_R6M
이용개월수_D페이_R6M
이용금액_간편결제_R6M
이용금액_A페이_R6M
이용금액_B페이_R6M
이용금액_C페이_R6M
이용금액_D페이_R6M
이용건수_간편결제_R6M
이용건수_A페이_R6M
이용건수_B페이_R6M
이용건수_C페이_R6M
이용건수_D페이_R6M
이용금액_간편결제_R3M
이용금액_A페이_R3M
이용금액_B페이_R3M
이용금액_C페이_R3M
이용금액_D페이_R3M
이용건수_간편결제_R3M
이용건수_A페이_R3M
이용건수_B페이_R3M
이용건수_C페이_R3M
이용건수_D페이_R3M
이용금액_간편결제_B0M
이용금액_A페이_B0M
이용금액_B페이_B0M
이용금액_C페이_B0M
이용금액_D페이_B0M
이용건수_간편결제_B0M
이용건수_A페이_B0M
이용건수_B페이_B0M
이용건수_C페이_B0M
이용건수_D페이_B0M
이용개월수_선결제_R6M
이용횟수_선결제_R6M
이용금액_선결제_R6M
이용건수_선결제_R6M
이용횟수_선결제_R3M
이용금액_선결제_R3M
이용건수_선결제_R3M
이용횟수_선결제_B0M
이용금액_선결제_B0M
이용건수_선결제_B0M
이용횟수_연체_R6M
이용금액_연체_R6M
이용횟수_연체_R3M
이용금액_연체_R3M
이용횟수_연체_B0M
이용금액_연체_B0M
이용개월수_전체_R6M
이용개월수_전체_R3M
이용개월수_결제일_R6M
이용개월수_결제일_R3M
가맹점매출금액_B1M
가맹점매출금액_B2M
정상청구원금_B0M
선입금원금_B0M
정상입금원금_B0M
연체입금원금_B0M
정상청구원금_B2M
선입금원금_B2M
정상입금원금_B2M
연체입금원금_B2M
정상청구원금_B5M
선입금원금_B5M
정상입금원금_B5M
연체입금원금_B5M
건수_할부전환_R6M
건수_할부전환_R3M
금액_할부전환_R6M
금액_할부전환_R3M
연속무실적개월수_기본_24M_카드
연속유실적개월수_기본_24M_카드
신청건수_ATM_CA_B0
신청건수_ATM_CA_R6M
신청건수_ATM_CL_R6M
승인거절건수_B0M
승인거절건수_한도초과_B0M
승인거절건수_BL_B0M
승인거절건수_R3M
승인거절건수_한도초과_R3M
승인거절건수_BL_R3M
승인거절건수_입력오류_R3M
승인거절건수_기타_R3M
이용금액대
컨택건수_카드론_TM_B0M
컨택건수_리볼빙_TM_B0M
컨택건수_이용유도_TM_B0M
컨택건수_보험_TM_B0M
컨택건수_카드론_LMS_B0M
컨택건수_CA_LMS_B0M
컨택건수_리볼빙_LMS_B0M
컨택건수_이용유도_LMS_B0M
컨택건수_카드론_EM_B0M
컨택건수_이용유도_EM_B0M
컨택건수_카드론_청구서_B0M
컨택건수_CA_청구서_B0M
컨택건수_이용유도_청구서_B0M
컨택건수_이용유도_인터넷_B0M
컨택건수_카드론_TM_R6M
컨택건수_CA_TM_R6M
컨택건수_리볼빙_TM_R6M
컨택건수_이용유도_TM_R6M
컨택건수_신용발급_TM_R6M
컨택건수_부대서비스_TM_R6M
컨택건수_포인트소진_TM_R6M
컨택건수_보험_TM_R6M
컨택건수_카드론_LMS_R6M
컨택건수_CA_LMS_R6M
컨택건수_리볼빙_LMS_R6M
컨택건수_이용유도_LMS_R6M
컨택건수_카드론_EM_R6M
컨택건수_이용유도_EM_R6M
컨택건수_카드론_청구서_R6M
컨택건수_CA_청구서_R6M
컨택건수_이용유도_청구서_R6M
컨택건수_이용유도_인터넷_R6M
컨택건수_이용유도_당사앱_R6M
컨택건수_채권_B0M
컨택건수_채권_R6M
캠페인접촉건수_R12M
캠페인접촉일수_R12M
ID
Segment.1

In [14]:
X = train_df.drop(columns=['ID', 'Unnamed: 0.1', 'Segment.1', 'Segment'])
Y = train_df['Segment']

1. 738개의 열을 어떻게 뽑아내서 붙일 것인가?

In [15]:
#팀에서 시계열 데이터를 다룰 수 있다면 시계열 데이터로 보기
#교수님은 이 데이터를 시계열로 보지 않고 하나의 데이터로 봄
for i in train_df.columns:
  print(i)

Unnamed: 0.1
대표결제일
대표결제방법코드
대표청구지고객주소구분코드
대표청구서수령지구분코드
청구서수령방법
청구서발송여부_B0
청구서발송여부_R3M
청구서발송여부_R6M
청구금액_B0
청구금액_R3M
청구금액_R6M
포인트_마일리지_건별_B0M
포인트_마일리지_건별_R3M
포인트_포인트_건별_B0M
포인트_포인트_건별_R3M
포인트_마일리지_월적립_B0M
포인트_마일리지_월적립_R3M
포인트_포인트_월적립_B0M
포인트_포인트_월적립_R3M
포인트_적립포인트_R12M
포인트_적립포인트_R3M
포인트_이용포인트_R12M
포인트_이용포인트_R3M
포인트_잔여포인트_B0M
마일_적립포인트_R12M
마일_적립포인트_R3M
마일_이용포인트_R12M
마일_이용포인트_R3M
마일_잔여포인트_B0M
할인건수_R3M
할인금액_R3M
할인건수_B0M
할인금액_B0M
할인금액_청구서_R3M
할인금액_청구서_B0M
상환개월수_결제일_R6M
상환개월수_결제일_R3M
선결제건수_R6M
선결제건수_R3M
연체건수_R6M
연체건수_R3M
혜택수혜금액_R3M
포인트_마일리지_환산_B0M
혜택수혜금액
최초한도금액
카드이용한도금액
CA한도금액
일시상환론한도금액
월상환론한도금액
CA이자율_할인전
CL이자율_할인전
RV일시불이자율_할인전
RV현금서비스이자율_할인전
RV신청일자
RV약정청구율
RV최소결제비율
자발한도감액횟수_R12M
자발한도감액금액_R12M
자발한도감액후경과월
강제한도감액횟수_R12M
강제한도감액금액_R12M
강제한도감액후경과월
한도증액횟수_R12M
한도증액금액_R12M
한도증액후경과월
상향가능한도금액
상향가능CA한도금액
카드론동의여부
월상환론상향가능한도금액
RV전환가능여부
일시불ONLY전환가능여부
카드이용한도금액_B1M
카드이용한도금액_B2M
특별한도보유여부_R3M
연체감액여부_R3M
한도심사요청건수
한도요청거절건수
한도심사요청후경과월
한도심사거절후경과월
시장단기연체여부_R6M
rv최초시작후경과일
증감율_이용건수_신용_전월
증감율_이용건수_신판_전월
증감율_이용건수_일시불_전월
증감율_이용건수_할부_전월
증감율_이용건수_CA_전월
증감율_이용건수_체크_전월
증감율_이용건수_카드론_전월
증감율_이용금액_신용_전월
증감율_이용금액_신판_전월
증감율_이용금액_일시불_전월
증감율_이용금액_할부_전월
증감율_이용금액_CA_전월
증감율_이용금액_체크_전월
증감율_이용금액_카드론_전월
증감율_이용건수_신용_분기
증감율_이용건수_신판_분기
증감율_이용건수_일시불_분기
증감율_이용건수_할부_분기
증감율_이용건수_CA_분기
증감율_이용건수_체크_분기
증감율_이용건수_카드론_분기
증감율_이용금액_신용_분기
증감율_이용금액_신판_분기
증감율_이용금액_일시불_분기
증감율_이용금액_할부_분기
증감율_이용금액_CA_분기
증감율_이용금액_체크_분기
증감율_이용금액_카드론_분기
잔액_신판평균한도소진율_r6m
잔액_신판최대한도소진율_r6m
잔액_신판평균한도소진율_r3m
잔액_신판최대한도소진율_r3m
잔액_신판ca평균한도소진율_r6m
잔액_신판ca최대한도소진율_r6m
잔액_신판ca평균한도소진율_r3m
잔액_신판ca최대한도소진율_r3m
변동률_일시불평잔
변동률_RV일시불평잔
변동률_할부평잔
변동률_CA평잔
변동률_RVCA평잔
변동률_카드론평잔
변동률_잔액_B1M
변동률_잔액_일시불_B1M
변동률_잔액_CA_B1M
혜택수혜율_R3M
혜택수혜율_B0M
Unnamed: 0
남녀구분코드
연령
Segment
회원여부_이용가능
회원여부_이용가능_CA
회원여부_이용가능_카드론
소지여부_신용
소지카드수_유효_신용
소지카드수_이용가능_신용
입회일자_신용
입회경과개월수_신용
회원여부_연체
이용거절여부_카드론
동의여부_한도증액안내
수신거부여부_TM
수신거부여부_DM
수신거부여부_메일
수신거부여부_SMS
가입통신회사코드
탈회횟수_누적
최종탈회후경과월
탈회횟수_발급6개월이내
탈회횟수_발급1년이내
거주시도명
직장시도명
마케팅동의여부
유효카드수_신용체크
유효카드수_신용
유효카드수_신용_가족
유효카드수_체크
유효카드수_체크_가족
이용가능카드수_신용체크
이용가능카드수_신용
이용가능카드수_신용_가족
이용가능카드수_체크
이용카드수_신용체크
이용카드수_신용
이용카드수_신용_가족
이용카드수_체크
이용금액_R3M_신용체크
이용금액_R3M_신용
이용금액_R3M_신용_가족
이용금액_R3M_체크
_1순위카드이용금액
_1순위카드이용건수
_1순위신용체크구분
_2순위카드이용금액
_2순위카드이용건수
_2순위신용체크구분
최종유효년월_신용_이용가능
최종유효년월_신용_이용
최종카드발급일자
보유여부_해외겸용_본인
이용가능여부_해외겸용_본인
이용여부_3M_해외겸용_본인
보유여부_해외겸용_신용_본인
이용가능여부_해외겸용_신용_본인
이용여부_3M_해외겸용_신용_본인
연회비발생카드수_B0M
기본연회비_B0M
제휴연회비_B0M
상품관련면제카드수_B0M
카드신청건수
Life_Stage
최종카드발급경과월
인입횟수_ARS_R6M
이용메뉴건수_ARS_R6M
인입일수_ARS_R6M
인입월수_ARS_R6M
인입후경과월_ARS
인입횟수_ARS_B0M
이용메뉴건수_ARS_B0M
인입일수_ARS_B0M
방문횟수_PC_R6M
방문일수_PC_R6M
방문월수_PC_R6M
방문후경과월_PC_R6M
방문횟수_앱_R6M
방문일수_앱_R6M
방문월수_앱_R6M
방문후경과월_앱_R6M
방문횟수_모바일웹_R6M
방문일수_모바일웹_R6M
방문월수_모바일웹_R6M
방문후경과월_모바일웹_R6M
방문횟수_PC_B0M
방문일수_PC_B0M
방문횟수_앱_B0M
방문일수_앱_B0M
방문횟수_모바일웹_B0M
방문일수_모바일웹_B0M
인입횟수_IB_R6M
인입일수_IB_R6M
인입월수_IB_R6M
이용메뉴건수_IB_R6M
인입후경과월_IB_R6M
인입횟수_IB_B0M
인입일수_IB_B0M
이용메뉴건수_IB_B0M
인입불만후경과월_IB_R6M
상담건수_B0M
IB문의건수_사용승인내역_B0M
IB문의건수_선결제_B0M
IB문의건수_CL_RV_B0M
IB문의건수_CS_B0M
상담건수_R6M
IB문의건수_사용승인내역_R6M
IB문의건수_한도_R6M
IB문의건수_선결제_R6M
IB문의건수_결제_R6M
IB문의건수_할부_R6M
IB문의건수_정보변경_R6M
IB문의건수_결제일변경_R6M
IB문의건수_비밀번호_R6M
IB문의건수_SMS_R6M
IB문의건수_포인트_R6M
IB문의건수_카드발급_R6M
IB문의건수_BL_R6M
IB문의건수_분실도난_R6M
IB문의건수_CA_R6M
IB문의건수_CL_RV_R6M
IB문의건수_CS_R6M
불만제기후경과월_R12M
당사멤버쉽_방문횟수_B0M
당사멤버쉽_방문횟수_R6M
당사멤버쉽_방문월수_R6M
OS구분코드
홈페이지_금융건수_R6M
홈페이지_선결제건수_R6M
홈페이지_금융건수_R3M
홈페이지_선결제건수_R3M
잔액_일시불_B0M
잔액_할부_B0M
잔액_현금서비스_B0M
잔액_리볼빙일시불이월_B0M
잔액_리볼빙CA이월_B0M
잔액_카드론_B0M
월중평잔_일시불_B0M
월중평잔_할부_B0M
월중평잔_CA_B0M
연체일자_B0M
연체잔액_B0M
연체잔액_일시불_B0M
연체잔액_할부_B0M
연체잔액_현금서비스_B0M
연체잔액_카드론_B0M
잔액_현금서비스_B1M
잔액_현금서비스_B2M
잔액_카드론_B1M
잔액_카드론_B2M
잔액_카드론_B3M
잔액_카드론_B4M
잔액_카드론_B5M
잔액_할부_B1M
잔액_할부_B2M
잔액_일시불_B1M
잔액_일시불_B2M
연체일수_B1M
연체일수_B2M
연체원금_B1M
연체원금_B2M
연체일수_최근
연체원금_최근
최종연체회차
RV_평균잔액_R12M
RV_최대잔액_R12M
RV_평균잔액_R6M
RV_최대잔액_R6M
RV_평균잔액_R3M
RV_최대잔액_R3M
잔액_할부_유이자_B0M
잔액_할부_무이자_B0M
잔액_할부_해외_B0M
연체잔액_RV일시불_B0M
연체잔액_CA_B0M
월중평잔
월중평잔_일시불
월중평잔_RV일시불
월중평잔_할부
월중평잔_CA
월중평잔_카드론
평잔_3M
평잔_일시불_3M
평잔_일시불_해외_3M
평잔_RV일시불_3M
평잔_RV일시불_해외_3M
평잔_할부_3M
평잔_할부_해외_3M
평잔_CA_3M
평잔_CA_해외_3M
평잔_카드론_3M
평잔_6M
평잔_일시불_6M
평잔_일시불_해외_6M
평잔_RV일시불_6M
평잔_RV일시불_해외_6M
평잔_할부_6M
평잔_할부_해외_6M
평잔_CA_6M
평잔_CA_해외_6M
평잔_카드론_6M
최종이용일자_기본
최종이용일자_신판
최종이용일자_CA
최종이용일자_카드론
최종이용일자_체크
최종이용일자_일시불
최종이용일자_할부
이용건수_신용_B0M
이용건수_신판_B0M
이용건수_일시불_B0M
이용건수_할부_B0M
이용건수_할부_유이자_B0M
이용건수_할부_무이자_B0M
이용건수_CA_B0M
이용건수_체크_B0M
이용건수_카드론_B0M
이용금액_일시불_B0M
이용금액_할부_B0M
이용금액_할부_유이자_B0M
이용금액_할부_무이자_B0M
이용금액_CA_B0M
이용금액_체크_B0M
이용금액_카드론_B0M
이용후경과월_신용
이용후경과월_신판
이용후경과월_일시불
이용후경과월_할부
이용후경과월_할부_유이자
이용후경과월_할부_무이자
이용후경과월_부분무이자
이용후경과월_CA
이용후경과월_체크
이용후경과월_카드론
이용건수_신용_R12M
이용건수_신판_R12M
이용건수_일시불_R12M
이용건수_할부_R12M
이용건수_할부_유이자_R12M
이용건수_할부_무이자_R12M
이용건수_부분무이자_R12M
이용건수_CA_R12M
이용건수_체크_R12M
이용건수_카드론_R12M
이용금액_일시불_R12M
이용금액_할부_R12M
이용금액_할부_유이자_R12M
이용금액_할부_무이자_R12M
이용금액_부분무이자_R12M
이용금액_CA_R12M
이용금액_체크_R12M
이용금액_카드론_R12M
최대이용금액_일시불_R12M
최대이용금액_할부_R12M
최대이용금액_할부_유이자_R12M
최대이용금액_할부_무이자_R12M
최대이용금액_부분무이자_R12M
최대이용금액_CA_R12M
최대이용금액_체크_R12M
최대이용금액_카드론_R12M
이용개월수_신용_R12M
이용개월수_신판_R12M
이용개월수_일시불_R12M
이용개월수_할부_R12M
이용개월수_할부_유이자_R12M
이용개월수_할부_무이자_R12M
이용개월수_부분무이자_R12M
이용개월수_CA_R12M
이용개월수_체크_R12M
이용개월수_카드론_R12M
이용건수_신용_R6M
이용건수_신판_R6M
이용건수_일시불_R6M
이용건수_할부_R6M
이용건수_할부_유이자_R6M
이용건수_할부_무이자_R6M
이용건수_부분무이자_R6M
이용건수_CA_R6M
이용건수_체크_R6M
이용건수_카드론_R6M
이용금액_일시불_R6M
이용금액_할부_R6M
이용금액_할부_유이자_R6M
이용금액_할부_무이자_R6M
이용금액_부분무이자_R6M
이용금액_CA_R6M
이용금액_체크_R6M
이용금액_카드론_R6M
이용개월수_신용_R6M
이용개월수_신판_R6M
이용개월수_일시불_R6M
이용개월수_할부_R6M
이용개월수_할부_유이자_R6M
이용개월수_할부_무이자_R6M
이용개월수_부분무이자_R6M
이용개월수_CA_R6M
이용개월수_체크_R6M
이용개월수_카드론_R6M
이용건수_신용_R3M
이용건수_신판_R3M
이용건수_일시불_R3M
이용건수_할부_R3M
이용건수_할부_유이자_R3M
이용건수_할부_무이자_R3M
이용건수_부분무이자_R3M
이용건수_CA_R3M
이용건수_체크_R3M
이용건수_카드론_R3M
이용금액_일시불_R3M
이용금액_할부_R3M
이용금액_할부_유이자_R3M
이용금액_할부_무이자_R3M
이용금액_부분무이자_R3M
이용금액_CA_R3M
이용금액_체크_R3M
이용금액_카드론_R3M
이용개월수_신용_R3M
이용개월수_신판_R3M
이용개월수_일시불_R3M
이용개월수_할부_R3M
이용개월수_할부_유이자_R3M
이용개월수_할부_무이자_R3M
이용개월수_부분무이자_R3M
이용개월수_CA_R3M
이용개월수_체크_R3M
이용개월수_카드론_R3M
이용가맹점수
이용금액_해외
쇼핑_도소매_이용금액
쇼핑_백화점_이용금액
쇼핑_마트_이용금액
쇼핑_슈퍼마켓_이용금액
쇼핑_편의점_이용금액
쇼핑_아울렛_이용금액
쇼핑_온라인_이용금액
쇼핑_기타_이용금액
교통_주유이용금액
교통_정비이용금액
교통_통행료이용금액
교통_버스지하철이용금액
교통_택시이용금액
교통_철도버스이용금액
여유_운동이용금액
여유_Pet이용금액
여유_공연이용금액
여유_공원이용금액
여유_숙박이용금액
여유_항공이용금액
여유_기타이용금액
납부_통신비이용금액
납부_관리비이용금액
납부_가스전기료이용금액
납부_보험료이용금액
납부_기타이용금액
_1순위업종
_1순위업종_이용금액
_2순위업종
_2순위업종_이용금액
_3순위업종
_3순위업종_이용금액
_1순위쇼핑업종
_1순위쇼핑업종_이용금액
_2순위쇼핑업종
_2순위쇼핑업종_이용금액
_3순위쇼핑업종
_3순위쇼핑업종_이용금액
_1순위교통업종
_1순위교통업종_이용금액
_2순위교통업종
_2순위교통업종_이용금액
_3순위교통업종
_3순위교통업종_이용금액
_1순위여유업종
_1순위여유업종_이용금액
_2순위여유업종
_2순위여유업종_이용금액
_3순위여유업종
_3순위여유업종_이용금액
_1순위납부업종
_1순위납부업종_이용금액
_2순위납부업종
_2순위납부업종_이용금액
_3순위납부업종
_3순위납부업종_이용금액
할부건수_3M_R12M
할부건수_6M_R12M
할부건수_12M_R12M
할부건수_14M_R12M
할부금액_3M_R12M
할부금액_6M_R12M
할부금액_12M_R12M
할부금액_14M_R12M
할부건수_유이자_3M_R12M
할부건수_유이자_6M_R12M
할부건수_유이자_12M_R12M
할부금액_유이자_3M_R12M
할부금액_유이자_6M_R12M
할부금액_유이자_12M_R12M
할부금액_유이자_14M_R12M
할부건수_무이자_3M_R12M
할부건수_무이자_6M_R12M
할부건수_무이자_12M_R12M
할부금액_무이자_3M_R12M
할부금액_무이자_6M_R12M
할부금액_무이자_12M_R12M
할부금액_무이자_14M_R12M
할부금액_부분_12M_R12M
할부금액_부분_14M_R12M
RP건수_B0M
RP금액_B0M
RP유형건수_B0M
RP건수_통신_B0M
RP건수_아파트_B0M
RP건수_제휴사서비스직접판매_B0M
RP건수_렌탈_B0M
RP건수_가스_B0M
RP건수_전기_B0M
RP건수_보험_B0M
RP건수_학습비_B0M
RP건수_교통_B0M
RP후경과월
RP후경과월_통신
RP후경과월_아파트
RP후경과월_제휴사서비스직접판매
RP후경과월_렌탈
RP후경과월_가스
RP후경과월_전기
RP후경과월_보험
RP후경과월_학습비
RP후경과월_교통
증감_RP건수_전월
증감_RP유형건수_전월
증감_RP건수_통신_전월
증감_RP건수_아파트_전월
증감_RP건수_제휴사서비스직접판매_전월
증감_RP건수_렌탈_전월
증감_RP건수_가스_전월
증감_RP건수_전기_전월
증감_RP건수_보험_전월
증감_RP건수_학습비_전월
증감_RP건수_교통_전월
최초카드론이용경과월
최종카드론이용경과월
카드론이용건수_누적
카드론이용월수_누적
카드론이용금액_누적
최종카드론_금융상환방식코드
최종카드론_신청경로코드
최종카드론_대출이율
최종카드론_대출일자
최종카드론_대출월수
최종카드론_거치개월수
최종카드론_대출금액
이용개월수_온라인_R6M
이용개월수_오프라인_R6M
이용금액_온라인_R6M
이용금액_오프라인_R6M
이용건수_온라인_R6M
이용건수_오프라인_R6M
이용금액_온라인_R3M
이용금액_오프라인_R3M
이용건수_온라인_R3M
이용건수_오프라인_R3M
이용금액_온라인_B0M
이용금액_오프라인_B0M
이용건수_온라인_B0M
이용건수_오프라인_B0M
이용개월수_페이_온라인_R6M
이용개월수_페이_오프라인_R6M
이용금액_페이_온라인_R6M
이용금액_페이_오프라인_R6M
이용건수_페이_온라인_R6M
이용건수_페이_오프라인_R6M
이용금액_페이_온라인_R3M
이용금액_페이_오프라인_R3M
이용건수_페이_온라인_R3M
이용건수_페이_오프라인_R3M
이용금액_페이_온라인_B0M
이용금액_페이_오프라인_B0M
이용건수_페이_온라인_B0M
이용건수_페이_오프라인_B0M
이용개월수_간편결제_R6M
이용개월수_당사기타_R6M
이용개월수_A페이_R6M
이용개월수_B페이_R6M
이용개월수_C페이_R6M
이용개월수_D페이_R6M
이용금액_간편결제_R6M
이용금액_A페이_R6M
이용금액_B페이_R6M
이용금액_C페이_R6M
이용금액_D페이_R6M
이용건수_간편결제_R6M
이용건수_A페이_R6M
이용건수_B페이_R6M
이용건수_C페이_R6M
이용건수_D페이_R6M
이용금액_간편결제_R3M
이용금액_A페이_R3M
이용금액_B페이_R3M
이용금액_C페이_R3M
이용금액_D페이_R3M
이용건수_간편결제_R3M
이용건수_A페이_R3M
이용건수_B페이_R3M
이용건수_C페이_R3M
이용건수_D페이_R3M
이용금액_간편결제_B0M
이용금액_A페이_B0M
이용금액_B페이_B0M
이용금액_C페이_B0M
이용금액_D페이_B0M
이용건수_간편결제_B0M
이용건수_A페이_B0M
이용건수_B페이_B0M
이용건수_C페이_B0M
이용건수_D페이_B0M
이용개월수_선결제_R6M
이용횟수_선결제_R6M
이용금액_선결제_R6M
이용건수_선결제_R6M
이용횟수_선결제_R3M
이용금액_선결제_R3M
이용건수_선결제_R3M
이용횟수_선결제_B0M
이용금액_선결제_B0M
이용건수_선결제_B0M
이용횟수_연체_R6M
이용금액_연체_R6M
이용횟수_연체_R3M
이용금액_연체_R3M
이용횟수_연체_B0M
이용금액_연체_B0M
이용개월수_전체_R6M
이용개월수_전체_R3M
이용개월수_결제일_R6M
이용개월수_결제일_R3M
가맹점매출금액_B1M
가맹점매출금액_B2M
정상청구원금_B0M
선입금원금_B0M
정상입금원금_B0M
연체입금원금_B0M
정상청구원금_B2M
선입금원금_B2M
정상입금원금_B2M
연체입금원금_B2M
정상청구원금_B5M
선입금원금_B5M
정상입금원금_B5M
연체입금원금_B5M
건수_할부전환_R6M
건수_할부전환_R3M
금액_할부전환_R6M
금액_할부전환_R3M
연속무실적개월수_기본_24M_카드
연속유실적개월수_기본_24M_카드
신청건수_ATM_CA_B0
신청건수_ATM_CA_R6M
신청건수_ATM_CL_R6M
승인거절건수_B0M
승인거절건수_한도초과_B0M
승인거절건수_BL_B0M
승인거절건수_R3M
승인거절건수_한도초과_R3M
승인거절건수_BL_R3M
승인거절건수_입력오류_R3M
승인거절건수_기타_R3M
이용금액대
컨택건수_카드론_TM_B0M
컨택건수_리볼빙_TM_B0M
컨택건수_이용유도_TM_B0M
컨택건수_보험_TM_B0M
컨택건수_카드론_LMS_B0M
컨택건수_CA_LMS_B0M
컨택건수_리볼빙_LMS_B0M
컨택건수_이용유도_LMS_B0M
컨택건수_카드론_EM_B0M
컨택건수_이용유도_EM_B0M
컨택건수_카드론_청구서_B0M
컨택건수_CA_청구서_B0M
컨택건수_이용유도_청구서_B0M
컨택건수_이용유도_인터넷_B0M
컨택건수_카드론_TM_R6M
컨택건수_CA_TM_R6M
컨택건수_리볼빙_TM_R6M
컨택건수_이용유도_TM_R6M
컨택건수_신용발급_TM_R6M
컨택건수_부대서비스_TM_R6M
컨택건수_포인트소진_TM_R6M
컨택건수_보험_TM_R6M
컨택건수_카드론_LMS_R6M
컨택건수_CA_LMS_R6M
컨택건수_리볼빙_LMS_R6M
컨택건수_이용유도_LMS_R6M
컨택건수_카드론_EM_R6M
컨택건수_이용유도_EM_R6M
컨택건수_카드론_청구서_R6M
컨택건수_CA_청구서_R6M
컨택건수_이용유도_청구서_R6M
컨택건수_이용유도_인터넷_R6M
컨택건수_이용유도_당사앱_R6M
컨택건수_채권_B0M
컨택건수_채권_R6M
캠페인접촉건수_R12M
캠페인접촉일수_R12M
ID
Segment.1

In [16]:
recent3 = [m for m in X.columns if 'R3M' in m]
print(recent3)
x_train = X[recent3]

['청구서발송여부_R3M', '청구금액_R3M', '포인트_마일리지_건별_R3M', '포인트_포인트_건별_R3M', '포인트_마일리지_월적립_R3M', '포인트_포인트_월적립_R3M', '포인트_적립포인트_R3M', '포인트_이용포인트_R3M', '마일_적립포인트_R3M', '마일_이용포인트_R3M', '할인건수_R3M', '할인금액_R3M', '할인금액_청구서_R3M', '상환개월수_결제일_R3M', '선결제건수_R3M', '연체건수_R3M', '혜택수혜금액_R3M', '특별한도보유여부_R3M', '연체감액여부_R3M', '혜택수혜율_R3M', '이용금액_R3M_신용체크', '이용금액_R3M_신용', '이용금액_R3M_신용_가족', '이용금액_R3M_체크', '홈페이지_금융건수_R3M', '홈페이지_선결제건수_R3M', 'RV_평균잔액_R3M', 'RV_최대잔액_R3M', '이용건수_신용_R3M', '이용건수_신판_R3M', '이용건수_일시불_R3M', '이용건수_할부_R3M', '이용건수_할부_유이자_R3M', '이용건수_할부_무이자_R3M', '이용건수_부분무이자_R3M', '이용건수_CA_R3M', '이용건수_체크_R3M', '이용건수_카드론_R3M', '이용금액_일시불_R3M', '이용금액_할부_R3M', '이용금액_할부_유이자_R3M', '이용금액_할부_무이자_R3M', '이용금액_부분무이자_R3M', '이용금액_CA_R3M', '이용금액_체크_R3M', '이용금액_카드론_R3M', '이용개월수_신용_R3M', '이용개월수_신판_R3M', '이용개월수_일시불_R3M', '이용개월수_할부_R3M', '이용개월수_할부_유이자_R3M', '이용개월수_할부_무이자_R3M', '이용개월수_부분무이자_R3M', '이용개월수_CA_R3M', '이용개월수_체크_R3M', '이용개월수_카드론_R3M', '이용금액_온라인_R3M', '이용금액_오프라인_R3M', '이용건수_온라인_R3M', '이용건수_오프라인_R3M', '이용금액_페이_온라인_R3M', '이용금액_페이_오프라인_R3M', '이용건수_페이_온라인_R3M', '이용건수_페이_오프라인_R3M', '이용금액_간편결제_R3M', '이용금액_A페이_R3M', '이용금액_B페이_R3M', '이용금액_C페이_R3M', '이용금액_D페이_R3M', '이용건수_간편결제_R3M', '이용건수_A페이_R3M', '이용건수_B페이_R3M', '이용건수_C페이_R3M', '이용건수_D페이_R3M', '이용횟수_선결제_R3M', '이용금액_선결제_R3M', '이용건수_선결제_R3M', '이용횟수_연체_R3M', '이용금액_연체_R3M', '이용개월수_전체_R3M', '이용개월수_결제일_R3M', '건수_할부전환_R3M', '금액_할부전환_R3M', '승인거절건수_R3M', '승인거절건수_한도초과_R3M', '승인거절건수_BL_R3M', '승인거절건수_입력오류_R3M', '승인거절건수_기타_R3M']

In [17]:
x_train.head()

,청구서발송여부_R3M,청구금액_R3M,포인트_마일리지_건별_R3M,포인트_포인트_건별_R3M,포인트_마일리지_월적립_R3M,포인트_포인트_월적립_R3M,포인트_적립포인트_R3M,포인트_이용포인트_R3M,마일_적립포인트_R3M,마일_이용포인트_R3M,...,이용금액_연체_R3M,이용개월수_전체_R3M,이용개월수_결제일_R3M,건수_할부전환_R3M,금액_할부전환_R3M,승인거절건수_R3M,승인거절건수_한도초과_R3M,승인거절건수_BL_R3M,승인거절건수_입력오류_R3M,승인거절건수_기타_R3M
0,1,1678,0,0,0,0,0,0,0,0,...,0,3,3,0,0,0,0,0,0,0
1,1,7778,0,0,0,0,0,0,0,0,...,0,3,3,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,15957,0,3743,0,0,3743,2285,0,0,...,0,3,3,0,0,0,0,0,0,0
4,1,2661,0,0,0,0,0,0,0,0,...,0,3,3,0,0,0,0,0,0,0

In [18]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70560 entries, 0 to 70559
Data columns (total 88 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   청구서발송여부_R3M       70560 non-null  int64
 1   청구금액_R3M          70560 non-null  int64
 2   포인트_마일리지_건별_R3M   70560 non-null  int64
 3   포인트_포인트_건별_R3M    70560 non-null  int64
 4   포인트_마일리지_월적립_R3M  70560 non-null  int64
 5   포인트_포인트_월적립_R3M   70560 non-null  int64
 6   포인트_적립포인트_R3M     70560 non-null  int64
 7   포인트_이용포인트_R3M     70560 non-null  int64
 8   마일_적립포인트_R3M      70560 non-null  int64
 9   마일_이용포인트_R3M      70560 non-null  int64
 10  할인건수_R3M          70560 non-null  object
 11  할인금액_R3M          70560 non-null  int64
 12  할인금액_청구서_R3M      70560 non-null  int64
 13  상환개월수_결제일_R3M     70560 non-null  int64
 14  선결제건수_R3M         70560 non-null  int64
 15  연체건수_R3M          70560 non-null  int64
 16  혜택수혜금액_R3M        70560 non-null  int64
 17  특별한도보유여부_R3M      70560 non-null  int64
 18  연체감액여부_R3M        70560 non-null  int64
 19  혜택수혜율_R3M         56080 non-null  float64
 20  이용금액_R3M_신용체크     70560 non-null  int64
 21  이용금액_R3M_신용       70560 non-null  int64
 22  이용금액_R3M_신용_가족    70560 non-null  int64
 23  이용금액_R3M_체크       70560 non-null  int64
 24  홈페이지_금융건수_R3M     70560 non-null  int64
 25  홈페이지_선결제건수_R3M    70560 non-null  int64
 26  RV_평균잔액_R3M       70560 non-null  int64
 27  RV_최대잔액_R3M       70560 non-null  int64
 28  이용건수_신용_R3M       70560 non-null  int64
 29  이용건수_신판_R3M       70560 non-null  int64
 30  이용건수_일시불_R3M      70560 non-null  int64
 31  이용건수_할부_R3M       70560 non-null  int64
 32  이용건수_할부_유이자_R3M   70560 non-null  int64
 33  이용건수_할부_무이자_R3M   70560 non-null  int64
 34  이용건수_부분무이자_R3M    70560 non-null  int64
 35  이용건수_CA_R3M       70560 non-null  int64
 36  이용건수_체크_R3M       70560 non-null  int64
 37  이용건수_카드론_R3M      70560 non-null  int64
 38  이용금액_일시불_R3M      70560 non-null  int64
 39  이용금액_할부_R3M       70560 non-null  int64
 40  이용금액_할부_유이자_R3M   70560 non-null  int64
 41  이용금액_할부_무이자_R3M   70560 non-null  int64
 42  이용금액_부분무이자_R3M    70560 non-null  int64
 43  이용금액_CA_R3M       70560 non-null  int64
 44  이용금액_체크_R3M       70560 non-null  int64
 45  이용금액_카드론_R3M      70560 non-null  int64
 46  이용개월수_신용_R3M      70560 non-null  int64
 47  이용개월수_신판_R3M      70560 non-null  int64
 48  이용개월수_일시불_R3M     70560 non-null  int64
 49  이용개월수_할부_R3M      70560 non-null  int64
 50  이용개월수_할부_유이자_R3M  70560 non-null  int64
 51  이용개월수_할부_무이자_R3M  70560 non-null  int64
 52  이용개월수_부분무이자_R3M   70560 non-null  int64
 53  이용개월수_CA_R3M      70560 non-null  int64
 54  이용개월수_체크_R3M      70560 non-null  int64
 55  이용개월수_카드론_R3M     70560 non-null  int64
 56  이용금액_온라인_R3M      70560 non-null  int64
 57  이용금액_오프라인_R3M     70560 non-null  int64
 58  이용건수_온라인_R3M      70560 non-null  int64
 59  이용건수_오프라인_R3M     70560 non-null  int64
 60  이용금액_페이_온라인_R3M   70560 non-null  int64
 61  이용금액_페이_오프라인_R3M  70560 non-null  int64
 62  이용건수_페이_온라인_R3M   70560 non-null  int64
 63  이용건수_페이_오프라인_R3M  70560 non-null  int64
 64  이용금액_간편결제_R3M     70560 non-null  int64
 65  이용금액_A페이_R3M      70560 non-null  int64
 66  이용금액_B페이_R3M      70560 non-null  int64
 67  이용금액_C페이_R3M      70560 non-null  int64
 68  이용금액_D페이_R3M      70560 non-null  int64
 69  이용건수_간편결제_R3M     70560 non-null  int64
 70  이용건수_A페이_R3M      70560 non-null  int64
 71  이용건수_B페이_R3M      70560 non-null  int64
 72  이용건수_C페이_R3M      70560 non-null  int64
 73  이용건수_D페이_R3M      70560 non-null  int64
 74  이용횟수_선결제_R3M      70560 non-null  int64
 75  이용금액_선결제_R3M      70560 non-null  int64
 76  이용건수_선결제_R3M      70560 non-null  int64
 77  이용횟수_연체_R3M       70560 non-null  int64
 78  이용금액_연체_R3M       70560 non-null  int64
 79  이용개월수_전체_R3M      70560 non-null  int64
 80  이용개월수_결제일_R3M     70560 non-null  int64
 81  건수_할부전환_R3M       70560 non-null  int64
 82  금액_할부전환_R3M       70560 non-null  int64
 83  승인거절건수_R3M        70560 non-null  int64
 84  승인거절건수_한도초과_R3M   70560 non-null  int64
 85  승인거절건수_BL_R3M     70560 non-null  int64
 86  승인거절건수_입력오류_R3M   70560 non-null  int64
 87  승인거절건수_기타_R3M     70560 non-null  int64
dtypes: float64(1), int64(86), object(1)
memory usage: 47.4+ MB

In [19]:
name = [x for x in x_train.columns if x_train[x].dtype == 'object']

In [20]:
name

['할인건수_R3M']

In [21]:
type(x_train)

pandas.core.frame.DataFrame

In [22]:
x_train['할인건수_R3M'].unique()

array(['1회 이상', '10회 이상', '20회 이상', '30회 이상'], dtype=object)

In [23]:
#라벨 인코딩을 하면 됨
#열을 구성해 오면 멘토링 시간에 봐줌

1. 모든 열을 출력해 본다
2. 최근 3개월 r3m만 추출해서 분류해 보자
3. 숫자가 아닌 것 object
4. 데이터 안에 카테고라가 몇 개인가 ['할인건수']
5. 할인건수를 잘 인코딩해서 열에 붙여 넣는다

In [24]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
x_train['할인건수_R3M'] = le.fit_transform(x_train['할인건수_R3M'])

<ipython-input-24-4dc9050408e3>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train['할인건수_R3M'] = le.fit_transform(x_train['할인건수_R3M'])

In [25]:
#DT, RF -> 계열이 과적합
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf = rf.fit(x_train, Y)

2. 클래스 불균형

In [26]:
Y.value_counts()

Segment
E    56505
D    10270
C     3753
A       28
B        4
Name: count, dtype: int64